# Generated by Django 2.0.6 on 2018-07-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180703_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
    ]
