# Generated by Django 2.0.6 on 2018-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to='courses/images', verbose_name='Imagen'),
        ),
    ]
