# Generated by Django 2.0.6 on 2018-07-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180703_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='hue', upload_to='courses/images', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
